'use client';
import { useEffect, useRef, useState } from 'react';
import { Compass, Footprints, RotateCcw, Sun, Moon, MapPin, X, Plus, Minus, ArrowUp, ArrowDown, ArrowLeft, ArrowRight } from 'lucide-react';
export default function Home() {
 const mount=useRef<HTMLDivElement>(null), api=useRef<any>(null);
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[walking,setWalking]=useState(false),[night,setNight]=useState(false),[selected,setSelected]=useState<any>(null),[visited,setVisited]=useState<string[]>([]);
 useEffect(()=>{let cleanup:(()=>void)|undefined,disposed=false; import('./park').then(({createPark})=>{if(disposed||!mount.current)return;const park=createPark(mount.current,setSelected,(id:string)=>setVisited(v=>v.includes(id)?v:[...v,id]));api.current=park;cleanup=park.dispose;setReady(true)}).catch(()=>setError('3D 场景暂时无法启动，请使用开启硬件加速的新版浏览器后刷新。'));return()=>{disposed=true;cleanup?.()}},[]);
 function mode(value:boolean){setWalking(value);api.current?.setWalking(value);setSelected(null)}
 useEffect(()=>{if(!ready)return;const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const definitions=[{name:'read_park_state',description:'读取当前公园视角、日夜状态、人物位置和已抵达的景点。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>api.current.getState()},{name:'configure_park_view',description:'切换俯瞰或步行视角与日夜效果，与页面按钮同步。不会替玩家打卡。',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['overview','walk']},night:{type:'boolean'}},required:['mode','night'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||!['overview','walk'].includes(input.mode)||typeof input.night!=='boolean'||Object.keys(input).some(k=>!['mode','night'].includes(k)))throw new Error('请输入有效的 mode 和 night');mode(input.mode==='walk');setNight(input.night);api.current.setNight(input.night);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return api.current.getState()}}];definitions.forEach(tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}});return()=>lifecycle.abort()},[ready]);
 return <main className={night?'park-app night':'park-app'}><div ref={mount} className="scene" aria-label="可拖动旋转、滚轮缩放的 3D 人才公园"/>
 <header className="masthead"><div className="brand-mark"><Compass size={26}/></div><div><div className="eyebrow">SHENZHEN · POCKET PARK</div><h1>人才公园<span>微缩漫游</span></h1></div></header>
 <div className="top-right"><span className="live-dot"/><span>{night?'灯火初上':'日落之前'}</span><button className="icon-button" aria-label={night?'切换日落':'切换夜景'} onClick={()=>{setNight(!night);api.current?.setNight(!night)}}>{night?<Sun size={19}/>:<Moon size={19}/>}</button></div>
 <section className="intro"><span className="chapter">01 / 城市里的小小绿洲</span><h2>把城市放慢一点。</h2><p>沿着湖岸，走一小段路。</p><div className="coordinates">22.51° N &nbsp; 113.94° E</div></section>
 <div className="view-tools"><button className="icon-button" aria-label="放大" onClick={()=>api.current?.zoom(.8)}><Plus size={19}/></button><button className="icon-button" aria-label="缩小" onClick={()=>api.current?.zoom(1.25)}><Minus size={19}/></button><span/><button className="icon-button" aria-label="重置视角" onClick={()=>api.current?.reset()}><RotateCcw size={18}/></button></div>
 <div className="compass"><span>N</span><Compass size={32} strokeWidth={1}/></div>
 {selected&&<section className="place-card"><button className="close" aria-label="关闭景点介绍" onClick={()=>setSelected(null)}><X size={18}/></button><div className="eyebrow">PARK DISCOVERY</div><h3>{selected.name}</h3><p>{selected.description}</p><span><MapPin size={14}/>{visited.includes(selected.id)?'已抵达 · 留下一段小小记忆':'进入漫游，走近这里打卡'}</span></section>}
 <footer className="bottom-bar"><div className="mode-controls"><button className={!walking?'active':''} onClick={()=>mode(false)}><Compass size={18}/>俯瞰公园</button><button className={walking?'active':''} onClick={()=>mode(true)}><Footprints size={18}/>进入漫游</button></div><div className="instruction">{walking?'W A S D / 方向键移动 · Shift 加速 · 拖动转视角':'拖动旋转 · 滚轮缩放 · 点击地标探索'}</div><div className="stamp-count"><MapPin size={17}/><strong>{visited.length}<span> / 4</span></strong><span>漫游印记</span></div></footer>
 {walking&&<div className="touch-pad">{[['ArrowUp',ArrowUp],['ArrowLeft',ArrowLeft],['ArrowDown',ArrowDown],['ArrowRight',ArrowRight]].map(([key,Icon]:any)=><button key={key} aria-label={key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);api.current?.key(key,true)}} onPointerUp={()=>api.current?.key(key,false)} onPointerCancel={()=>api.current?.key(key,false)}><Icon size={24}/></button>)}</div>}
 <div className="map-note">人才公园灵感地图 · 艺术化布局</div>{!ready&&<div className="loading"><Compass size={36}/><p>{error||'正在展开你的小小公园…'}</p>{error&&<button onClick={()=>location.reload()}>重新加载</button>}</div>}</main>
}
