import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { boundary, lake, northWater, starBridge, piBridge, northBridge, shoreWalk, northWalk, southWalk, tideCenter, spawn, places, inside, isWater, distanceToPath, groundHeight, bridgeHeight, walkable, type Point } from './geography';

export const PLACES = places;

export function createPark(host:HTMLElement,onSelect:(p:typeof PLACES[number])=>void,onVisit:(id:string)=>void){
 const scene=new THREE.Scene(); scene.background=new THREE.Color('#d8e7e5');scene.fog=new THREE.Fog('#d8e7e5',160,300);
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;host.appendChild(renderer.domElement);
 const camera=new THREE.PerspectiveCamera(42,host.clientWidth/host.clientHeight,.1,400);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.maxPolarAngle=Math.PI*.47;controls.minPolarAngle=.18;controls.enablePan=false;controls.minDistance=40;controls.maxDistance=210;controls.target.set(0,1,0);
 const hemi=new THREE.HemisphereLight('#d5f8ff','#57684a',2.6);scene.add(hemi);
 const sun=new THREE.DirectionalLight('#ffe0ab',3.1);sun.position.set(-45,65,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-75,right:75,top:65,bottom:-65,near:1,far:180});sun.shadow.normalBias=.08;sun.shadow.bias=-.0002;scene.add(sun);
 const fill=new THREE.DirectionalLight('#8ed4e6',.6);fill.position.set(45,20,-40);scene.add(fill);
 const mat=(color:string,roughness=.8)=>new THREE.MeshStandardMaterial({color,roughness,flatShading:true});
 const grass=mat('#83ae63'),grassLight=mat('#a5bd75'),earth=mat('#879984'),sand=mat('#d6d4b0'),pathmat=mat('#f1dfb8'),white=mat('#f2f0d9'),wood=mat('#a57c50'),bark=mat('#7d7250'),metal=mat('#385c61');
 const boxG=new THREE.BoxGeometry(1,1,1),cylG=new THREE.CylinderGeometry(1,1,1,12);
 function mesh(g:THREE.BufferGeometry,m:THREE.Material,x=0,y=0,z=0,parent:THREE.Object3D=scene){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 function box(x:number,y:number,z:number,w:number,h:number,d:number,m:THREE.Material,p:THREE.Object3D=scene){const o=mesh(boxG,m,x,y,z,p);o.scale.set(w,h,d);return o}
 function cyl(x:number,y:number,z:number,r:number,h:number,m:THREE.Material,p:THREE.Object3D=scene){const o=mesh(cylG,m,x,y,z,p);o.scale.set(r,h,r);return o}
 function ellipse(rx:number,rz:number,y:number,m:THREE.Material,x=0,z=0,depth=.1){const o=mesh(new THREE.CylinderGeometry(1,1,depth,100),m,x,y,z);o.scale.set(rx,1,rz);return o}
 function line(points:THREE.Vector3[],radius:number,m:THREE.Material){return mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),Math.max(12,points.length*3),radius,6,false),m)}
 function ring(rx:number,rz:number,width:number,y:number,m:THREE.Material,cx=0,cz=0){const vertices:number[]=[],indices:number[]=[];for(let i=0;i<=160;i++){const t=i/160*Math.PI*2;vertices.push(cx+(rx-width/2)*Math.cos(t),y,cz+(rz-width/2)*Math.sin(t),cx+(rx+width/2)*Math.cos(t),y,cz+(rz+width/2)*Math.sin(t));if(i<160){const a=i*2;indices.push(a,a+2,a+1,a+1,a+2,a+3)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setIndex(indices);g.computeVertexNormals();const o=mesh(g,m);o.material.side=THREE.DoubleSide;return o}

 function shape(points:Point[],y:number,m:THREE.Material,depth=0){const sh=new THREE.Shape();points.forEach((p,i)=>i?sh.lineTo(p[0],-p[1]):sh.moveTo(p[0],-p[1]));sh.closePath();const g=depth?new THREE.ExtrudeGeometry(sh,{depth,bevelEnabled:false}):new THREE.ShapeGeometry(sh);g.rotateX(-Math.PI/2);return mesh(g,m,0,y,0)}
 function ribbon(points:Point[],width:number,m:THREE.Material,y=.66,closed=false){const v:number[]=[],ix:number[]=[];const n=points.length;for(let i=0;i<n;i++){const p=points[i],a=points[i===0?(closed?n-1:0):i-1],b=points[i===n-1?(closed?0:n-1):i+1];const len=Math.hypot(b[0]-a[0],b[1]-a[1])||1,nx=-(b[1]-a[1])/len,nz=(b[0]-a[0])/len;v.push(p[0]+nx*width/2,y,p[1]+nz*width/2,p[0]-nx*width/2,y,p[1]-nz*width/2);if(i<n-1||closed){const j=(i+1)%n;ix.push(i*2,j*2,i*2+1,i*2+1,j*2,j*2+1)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(ix);g.computeVertexNormals();m.side=THREE.DoubleSide;return mesh(g,m)}
 const ground=mesh(new THREE.PlaneGeometry(2000,2000),mat('#d8e7e5'),0,-3.5,0);ground.rotation.x=-Math.PI/2;ground.castShadow=false;
 const block:Point[]=[[-58,-69],[51,-69],[53,59],[-58,59]];
 shape(block,-3,earth,3.5);shape(block,.51,mat('#c7d0c6'));
 shape(boundary,.53,grass);
 // Terrain triangles and walking height share the same modest relief model.
 const tv:number[]=[];for(let x=-47;x<46;x+=1.1)for(let z=-59;z<55;z+=1.1){for(const tri of [[[x,z],[x+1.1,z],[x,z+1.1]],[[x+1.1,z],[x+1.1,z+1.1],[x,z+1.1]]]){if(tri.every(p=>inside(p[0],p[1],boundary))){for(const p of tri)tv.push(p[0],groundHeight(p[0],p[1]),p[1])}}}const tg=new THREE.BufferGeometry();tg.setAttribute('position',new THREE.Float32BufferAttribute(tv,3));tg.computeVertexNormals();const terrainMat=mat('#779a58');terrainMat.side=THREE.DoubleSide;mesh(tg,terrainMat);
 const watermat=new THREE.ShaderMaterial({uniforms:{time:{value:0},night:{value:0}},vertexShader:`varying vec3 vWorld;void main(){vec4 w=modelMatrix*vec4(position,1.);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`varying vec3 vWorld;uniform float time;uniform float night;void main(){float ripple=sin(vWorld.x*3.+vWorld.z*1.6+time*.6)*sin(vWorld.z*3.4-vWorld.x*.9-time*.4);float glint=pow(max(0.,sin(vWorld.x*2.8+vWorld.z*4.1+time*.6)),32.)*.045;vec3 c=vec3(.19,.39,.38)+ripple*.012+glint;float band=exp(-pow((vWorld.x+14.+sin(vWorld.z*8.+time)*.22)/2.8,2.))*exp(-abs(vWorld.z+8.)*.025);c=mix(c,vec3(.055,.13,.18)+band*vec3(.23,.21,.11)*(0.45+0.35*sin(vWorld.z*9.+time)),night);gl_FragColor=vec4(c,1.);}`});
 for(const contour of [lake,northWater]){shape(contour,.72,watermat).castShadow=false;ribbon(contour,.4,mat('#bbc2ad'),.77,true)}
 ribbon(shoreWalk,2.4,pathmat,.79,true);ribbon(northWalk,2,pathmat,.79);ribbon(southWalk,1.8,pathmat,.8);
 const running:Point[]=shoreWalk.map(p=>[p[0]-.7,p[1]+.7]);ribbon(running,.45,mat('#62b3c6'),.81,true);
 // Public roads are outside the park rather than a ring of towers on its grass.
 const asphalt=mat('#81918f');ribbon([[-47,56],[28,56],[33,35],[41,0],[44,-30],[46,-58]],3.2,asphalt,.6);ribbon([[-34,-61],[46,-54]],3.3,asphalt,.6);ribbon([[-46,33],[-38,24],[-30,6],[-20,-30],[-9,-37],[-2,-57]],3.1,asphalt,.6);
 for(let i=0;i<35;i++)box(44-i*.44,.64,-45+i*2.8,.1,.02,.75,white);
 // Tidal square: concentric stone terraces around the circular lawn.
 const [tx,tz]=tideCenter;ellipse(5.9,5.9,.71,mat('#cbd0bc'),tx,tz,.2);for(let i=0;i<4;i++)ring(4.2+i*.44,4.2+i*.44,.35,.79+i*.04,i%2?white:sand,tx,tz);ellipse(3.85,3.85,.79,grassLight,tx,tz,.13);box(tx,.99,tz-1.7,2.2,.33,.55,white);
 // A flat roof pavilion near the western shore.
 const pavilionGlass=mat('#668986',.3);box(-37,1.35,20,2.4,1.5,7,pavilionGlass);box(-37,2.2,20,3.4,.2,7.8,white);for(let j=0;j<8;j++)box(-35.75,1.35,17+j*.9,.07,1.6,.06,white);
 const obstacles:{x:number,z:number,r:number}[]=[{x:-37,z:20,r:1.5}];
 let seed=129;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
 const trunks:THREE.Matrix4[]=[],crowns:THREE.Matrix4[]=[],colors:THREE.Color[]=[];const temp=new THREE.Object3D();
 function tree(x:number,z:number,scale=1){const y=groundHeight(x,z);trunks.push(new THREE.Matrix4().compose(new THREE.Vector3(x,y+scale,z),new THREE.Quaternion(),new THREE.Vector3(.10*scale,2*scale,.1*scale)));for(let j=0;j<3;j++){temp.position.set(x+(j-1)*.36*scale,y+(2.1+(j%2)*.45)*scale,z+(j%2)*.35*scale);temp.rotation.set(0,rand()*6,0);temp.scale.set(.9*scale,1.0*scale,.9*scale);temp.updateMatrix();crowns.push(temp.matrix.clone());colors.push(new THREE.Color().setHSL(.26+rand()*.05,.25+rand()*.13,.28+rand()*.12))}obstacles.push({x,z,r:.25*scale})}
 function clearPath(x:number,z:number){return Math.min(distanceToPath(x,z,shoreWalk,true),distanceToPath(x,z,piBridge),distanceToPath(x,z,starBridge),distanceToPath(x,z,northWalk),distanceToPath(x,z,southWalk),distanceToPath(x,z,northBridge))>2.0}
 for(let i=0;i<1800;i++){const x=-44+rand()*88,z=-57+rand()*109;if(!inside(x,z,boundary)||isWater(x,z)||distanceToPath(x,z,lake,true)<1.7||distanceToPath(x,z,northWater,true)<1.4||!clearPath(x,z)||Math.hypot(x-tx,z-tz)<7||Math.hypot(x+37,z-20)<5)continue;tree(x,z,.55+rand()*.55)}
 const ti=new THREE.InstancedMesh(cylG,bark,trunks.length),ci=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),mat('#6b8c4d'),crowns.length);trunks.forEach((m,i)=>ti.setMatrixAt(i,m));crowns.forEach((m,i)=>{ci.setMatrixAt(i,m);ci.setColorAt(i,colors[i])});ti.castShadow=true;ci.castShadow=true;ci.receiveShadow=true;scene.add(ti,ci);
 // Small offshore wetlands articulate the south edge.
 for(const [x,z,rx,rz] of [[-23,33,2,1],[-16,34,1.8,.8],[-8,32,2.2,1.3],[0,29.7,2.2,1.1],[12,31,1.7,.8]]){ellipse(rx,rz,.86,grassLight,x,z,.25);for(let i=0;i<8;i++){const a=rand()*6.28;cyl(x+Math.cos(a)*rx*.65,1.25,z+Math.sin(a)*rz*.6,.035,.8,mat('#a5aa71'))}}
 // Spring Bamboo: curved profile, 56 facade ribs, 28-column diagrid at both ends.
 const tower=new THREE.Group();tower.position.set(-18,.6,-46);scene.add(tower);const height=39.2;
 function radius(t:number){return 3.05*(1-.19*t-.81*Math.pow(t,5.0))+.04}
 const profile:THREE.Vector2[]=[];for(let i=0;i<=64;i++)profile.push(new THREE.Vector2(radius(i/64),i/64*height));
 const glass=mat('#78959e',.24);glass.metalness=.65;glass.flatShading=false;mesh(new THREE.LatheGeometry(profile,56),glass,0,0,0,tower);
 const ribMat=mat('#d1d7d1',.42);for(let j=0;j<56;j++){const a=j/56*Math.PI*2,pts:THREE.Vector3[]=[];for(let k=0;k<=32;k++){const t=.13+k/32*.73;pts.push(new THREE.Vector3(Math.cos(a)*(radius(t)+.025),t*height,Math.sin(a)*(radius(t)+.025)))}const rib=mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),32,.028,3,false),ribMat,0,0,0,tower);rib.castShadow=false}
 for(let j=0;j<28;j++){const angle=j/28*Math.PI*2;for(const direction of [-1,1])for(const top of [false,true]){const pts:THREE.Vector3[]=[];for(let k=0;k<=12;k++){const f=k/12,t=top?.86+f*.14:f*.13,a=angle+direction*(top?(1-f):f)*Math.PI/56;pts.push(new THREE.Vector3(Math.cos(a)*(radius(t)+.035),t*height,Math.sin(a)*(radius(t)+.035)))}mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),12,.045,4,false),ribMat,0,0,0,tower)}}
 for(let i=1;i<68;i++){const t=i/68;const hoop=mesh(new THREE.TorusGeometry(radius(t)+.02,.015,3,56),ribMat,0,t*height,0,tower);hoop.rotation.x=Math.PI/2;hoop.castShadow=false}box(-18,.75,-46,9,.3,8,white);obstacles.push({x:-18,z:-46,r:4});
 const windowmat=new THREE.MeshStandardMaterial({color:'#bfd3d5',emissive:'#ffdaa0',emissiveIntensity:0,roughness:.35});
 // Simplified contextual volumes, with explicit footprints rather than a random skyline.
 for(const [x,z,w,d,h] of [[-28,-43,4,5,24],[-38,-45,5,5,19],[-39,-33,5,4,27],[-45,-21,4,5,16],[-46,-9,4.5,4,22],[-49,-41,4,5,13]]){box(x,.6+h/2,z,w,h,d,mat('#91a8ac',.35));box(x,h+.8,z,w*.95,.3,d*.95,white);for(let j=0;j<Math.floor(h/.65);j++)box(x,1+j*.65,z+d/2+.02,w*.85,.06,.04,windowmat)}
 // Northern sports-centre context: broad low roof, far lower than the tower.
 const roof=ellipse(15,7,2.0,white,14,-64,.7);roof.rotation.y=.12;ellipse(10,4.7,2.4,mat('#9bbaaf'),14,-64,.2);ring(13.5,6.1,.18,2.42,metal,14,-64);
 const lampMat=new THREE.MeshStandardMaterial({color:'#fff2c9',emissive:'#ffce7a',emissiveIntensity:.25});
 function footbridge(points:Point[],width:number,stars=false){ribbon(points,width,white,.94);const pts=points.map(p=>new THREE.Vector3(p[0],1.8,p[1]));for(const side of [-1,1]){const offset=pts.map((p,i)=>{const a=pts[Math.max(0,i-1)],b=pts[Math.min(pts.length-1,i+1)],v=b.clone().sub(a).normalize();return p.clone().add(new THREE.Vector3(-v.z,0,v.x).multiplyScalar(side*width*.46))});line(offset,.035,metal);for(let i=0;i<points.length-1;i++){const a=offset[i],b=offset[i+1],n=Math.ceil(a.distanceTo(b)/1.2);for(let j=0;j<n;j++){const p=a.clone().lerp(b,j/n);box(p.x,1.35,p.z,.04,.82,.04,metal)}}}if(stars){for(let i=0;i<30;i++){const t=(i+.5)/30,x=points[0][0]*(1-t)+points[1][0]*t,z=points[0][1]*(1-t)+points[1][1]*t;cyl(x+(i%2?.85:-.85),2.1,z,.075,2.3,white);box(x+(i%2?.85:-.85),3.3,z,.14,.15,.14,lampMat)}}}
 footbridge(starBridge,2.3,true);footbridge(piBridge,1.9);footbridge(northBridge,1.7);
 // Numerical railing panels, rather than an invented giant pi-shaped sculpture.
 const digitsCanvas=document.createElement('canvas');digitsCanvas.width=1024;digitsCanvas.height=64;const dc=digitsCanvas.getContext('2d')!;dc.fillStyle='#d1d7d0';dc.fillRect(0,0,1024,64);dc.fillStyle='#425f5d';dc.font='36px monospace';dc.fillText('π 3.14159265358979323846264338327950288419716939937510',8,45);const digitsTexture=new THREE.CanvasTexture(digitsCanvas);digitsTexture.colorSpace=THREE.SRGBColorSpace;const digitsMaterial=new THREE.MeshStandardMaterial({map:digitsTexture,side:THREE.DoubleSide});
 for(let i=0;i<piBridge.length-1;i++){const a=piBridge[i],b=piBridge[i+1],l=Math.hypot(b[0]-a[0],b[1]-a[1]);const panel=mesh(new THREE.PlaneGeometry(l,.37),digitsMaterial,(a[0]+b[0])/2,1.45,(a[1]+b[1])/2+.9);panel.rotation.y=-Math.atan2(b[1]-a[1],b[0]-a[0])}
 for(let i=0;i<shoreWalk.length;i+=2){const [x,z]=shoreWalk[i];cyl(x+.7,1.65,z,.04,1.9,metal);mesh(new THREE.SphereGeometry(.12,8,6),lampMat,x+.7,2.65,z);if(i%6===0){const bench=new THREE.Group();bench.position.set(x-1.3,.8,z);scene.add(bench);box(0,.45,0,1.4,.1,.48,wood,bench);box(0,.75,.22,1.4,.35,.08,wood,bench);for(const a of [-.48,.48])box(a,.22,0,.08,.45,.4,metal,bench)}}
 const duck=new THREE.Group();scene.add(duck);mesh(new THREE.SphereGeometry(.25,10,8),white,0,.9,0,duck).scale.set(1.4,.7,1);mesh(new THREE.SphereGeometry(.14,8,6),white,.25,1.08,0,duck);box(.4,1.07,0,.18,.06,.08,mat('#dcaa51'),duck);
 // Clickable place labels are functional map markers.
 const pickables:THREE.Object3D[]=[],markerGroups:THREE.Group[]=[];const textures:THREE.Texture[]=[digitsTexture];
 PLACES.forEach((p,index)=>{const g=new THREE.Group();g.position.set(p.x,4.5,p.z);scene.add(g);markerGroups.push(g);const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle='#f7fbef';ctx.beginPath();ctx.roundRect(3,5,506,112,56);ctx.fill();ctx.fillStyle='#28595a';ctx.font='600 42px Arial, Microsoft YaHei';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(`0${index+1}  ${p.name}`,256,64);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;textures.push(t);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,depthTest:false,transparent:true}));s.scale.set(8.5,2.12,1);s.userData.place=p;s.renderOrder=5;g.add(s);pickables.push(s);const pin=mesh(new THREE.OctahedronGeometry(.32),mat('#edb468'),p.x,1.9,p.z);pin.userData.place=p;pickables.push(pin)});
 // A small explorer with a backpack, articulated legs and a sun hat.
 const player=new THREE.Group();player.position.set(spawn[0],.83,spawn[1]);scene.add(player);const shirt=mat('#df8856'),skin=mat('#efd1a4'),pants=mat('#3b6267');
 const body=box(0,.85,0,.5,.62,.32,shirt,player);mesh(new THREE.SphereGeometry(.23,12,8),skin,0,1.4,0,player);cyl(0,1.58,0,.32,.07,sand,player);cyl(0,1.64,0,.23,.15,sand,player);box(0,.89,.23,.37,.45,.17,mat('#ddc28a'),player);
 const legs=[box(-.14,.3,0,.17,.55,.2,pants,player),box(.14,.3,0,.17,.55,.2,pants,player)];box(-.34,.85,0,.14,.53,.15,skin,player);box(.34,.85,0,.14,.53,.15,skin,player);
 const halo=mesh(new THREE.RingGeometry(.6,.7,36),new THREE.MeshBasicMaterial({color:'#fff0ad',side:THREE.DoubleSide}),0,.02,0,player);halo.rotation.x=-Math.PI/2;player.visible=false;
 let walking=false,night=false,frame=0,last=performance.now(),elapsed=0,selectedId='',dead=false;let jumpVelocity=0,airborne=false;const keys=new Set<string>(),visited=new Set<string>();
 const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let downX=0,downY=0;
 const pointerDown=(e:PointerEvent)=>{downX=e.clientX;downY=e.clientY};
 const pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-downX,e.clientY-downY)>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(pickables);if(hits.length)onSelect(hits[0].object.userData.place)};
 renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pointerUp);
 const keyDown=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&(['INPUT','TEXTAREA'].includes(e.target.tagName)||e.target.isContentEditable))return;if(walking&&e.code==='Space'){e.preventDefault();if(!e.repeat&&!airborne){jumpVelocity=6;airborne=true}return}if(walking&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase())};const keyUp=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const blur=()=>keys.clear();window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);
 function canWalk(x:number,z:number){return walkable(x,z)&&!obstacles.some(o=>(x-o.x)**2+(z-o.z)**2<(o.r+.25)**2)}
 function setWalking(value:boolean){walking=value;player.visible=value;keys.clear();jumpVelocity=0;airborne=false;player.position.y=(bridgeHeight(player.position.x,player.position.z)??groundHeight(player.position.x,player.position.z))+.05;if(value){controls.minDistance=5;controls.maxDistance=25;controls.maxPolarAngle=Math.PI*.47;controls.target.copy(player.position).add(new THREE.Vector3(0,1,0));camera.position.copy(controls.target).add(new THREE.Vector3(8,9,13))}else reset();controls.update()}
 function reset(){if(walking){controls.target.copy(player.position).add(new THREE.Vector3(0,1,0));camera.position.copy(controls.target).add(new THREE.Vector3(8,9,13))}else{controls.minDistance=40;controls.maxDistance=210;controls.target.set(0,1,0);const mobile=host.clientWidth<650;camera.position.set(mobile?121:92,mobile?136:101,mobile?145:114)}controls.update()}
 function setNight(value:boolean){night=value;scene.background=new THREE.Color(value?'#102b38':'#d8e7e5');(scene.fog as THREE.Fog).color.copy(scene.background);(ground.material as THREE.MeshStandardMaterial).color.set(value?'#102b38':'#d8e7e5');hemi.intensity=value?.85:2.6;sun.intensity=value?.5:3.1;sun.color.set(value?'#94b8e2':'#ffe0ab');lampMat.emissiveIntensity=value?4:.25;windowmat.emissiveIntensity=value?1.6:0;watermat.uniforms.night.value=value?1:0}
 const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};const observer=new ResizeObserver(resize);observer.observe(host);reset();
 function animate(now:number){if(dead)return;frame=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;elapsed+=dt;watermat.uniforms.time.value=elapsed;duck.position.set(-2+Math.cos(elapsed*.09)*4,0,8+Math.sin(elapsed*.09)*3);duck.rotation.y=-elapsed*.09;
 if(walking){let dx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),dz=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));if(dx||dz){const forward=camera.position.clone().sub(controls.target);forward.y=0;forward.normalize();const right=new THREE.Vector3(forward.z,0,-forward.x);const move=forward.multiplyScalar(dz).add(right.multiplyScalar(dx)).normalize().multiplyScalar(dt*(keys.has('shift')?7:3.8));const before=player.position.clone();if(canWalk(player.position.x+move.x,player.position.z))player.position.x+=move.x;if(canWalk(player.position.x,player.position.z+move.z))player.position.z+=move.z;player.rotation.y=Math.atan2(move.x,move.z)+Math.PI;const delta=player.position.clone().sub(before);camera.position.add(delta);controls.target.add(delta);legs[0].rotation.x=Math.sin(elapsed*12)*.5;legs[1].rotation.x=-legs[0].rotation.x;body.position.y=.85+Math.abs(Math.sin(elapsed*12))*.035}else{legs.forEach(l=>l.rotation.x=0)}
 const oldY=player.position.y;const floorY=(bridgeHeight(player.position.x,player.position.z)??groundHeight(player.position.x,player.position.z))+.05;if(airborne){player.position.y+=jumpVelocity*dt-9*dt*dt;jumpVelocity-=18*dt;if(player.position.y<=floorY){player.position.y=floorY;jumpVelocity=0;airborne=false}}else player.position.y=floorY;halo.position.y=floorY-player.position.y+.02;if(airborne){legs[0].rotation.x=-.35;legs[1].rotation.x=.25;body.position.y=.85}camera.position.y+=player.position.y-oldY;controls.target.y+=player.position.y-oldY;
 for(const p of PLACES){if(Math.hypot(player.position.x-p.x,player.position.z-p.z)<4&&!visited.has(p.id)){visited.add(p.id);onVisit(p.id);if(selectedId!==p.id){selectedId=p.id;onSelect(p)}}}}
 markerGroups.forEach((g,i)=>{g.position.y=4.5+Math.sin(elapsed*1.2+i)*.14;g.visible=!walking||player.position.distanceTo(g.position)<20});controls.update();renderer.render(scene,camera)}frame=requestAnimationFrame(animate);
 return {setWalking,setNight,reset,zoom:(f:number)=>{const v=camera.position.clone().sub(controls.target);v.multiplyScalar(f).clampLength(controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).add(v);controls.update()},key:(k:string,pressed:boolean)=>pressed?keys.add(k.toLowerCase()):keys.delete(k.toLowerCase()),getState:()=>({walking,night,visited:[...visited],position:{x:player.position.x,z:player.position.z}}),dispose:()=>{dead=true;cancelAnimationFrame(frame);observer.disconnect();controls.dispose();window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointerup',pointerUp);const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();scene.traverse(o=>{if(o instanceof THREE.Mesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m))}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();renderer.domElement.remove()}}
}
