import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {MEMORY_LOCATIONS,type MemoryLocation} from './locations';

export function createPlanet(host:HTMLElement,onEnter:(location:MemoryLocation)=>void,onSelect:(location:MemoryLocation)=>void){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#071b28');scene.fog=new THREE.FogExp2('#071b28',.008);
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;host.appendChild(renderer.domElement);
 const camera=new THREE.PerspectiveCamera(40,host.clientWidth/host.clientHeight,.1,300);camera.position.set(43,35,48);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.055;controls.enablePan=false;controls.minDistance=42;controls.maxDistance=90;controls.minPolarAngle=.18;controls.maxPolarAngle=Math.PI*.72;controls.target.set(0,3,0);
 scene.add(new THREE.HemisphereLight('#b9efff','#0a1821',2.2));const sun=new THREE.DirectionalLight('#ffd39b',4.2);sun.position.set(-35,60,28);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);const rim=new THREE.DirectionalLight('#4cb7d0',2.5);rim.position.set(35,5,-45);scene.add(rim);
 const textures:THREE.Texture[]=[];const materials:THREE.Material[]=[];const geometries:THREE.BufferGeometry[]=[];const remember=<T extends THREE.Material>(m:T)=>{materials.push(m);return m};const geometry=<T extends THREE.BufferGeometry>(g:T)=>{geometries.push(g);return g};
 const radius=20,root=new THREE.Group();root.rotation.y=-.14;scene.add(root);
 const ocean=new THREE.Mesh(geometry(new THREE.SphereGeometry(radius,64,40)),remember(new THREE.MeshStandardMaterial({color:'#0d6070',roughness:.5,metalness:.08,flatShading:true})));ocean.receiveShadow=true;root.add(ocean);
 const atmosphere=new THREE.Mesh(geometry(new THREE.SphereGeometry(radius*1.045,48,32)),remember(new THREE.MeshBasicMaterial({color:'#73dbeb',transparent:true,opacity:.10,side:THREE.BackSide})));root.add(atmosphere);
 const rings=new THREE.Mesh(geometry(new THREE.TorusGeometry(radius*1.18,.035,6,160)),remember(new THREE.MeshBasicMaterial({color:'#85e1e3',transparent:true,opacity:.2})));rings.rotation.x=Math.PI/2.7;root.add(rings);
 const landOutline:[number,number][]=[[-15,-7],[-11,-10],[-5,-11],[-1,-10],[3,-11],[8,-9],[13,-6],[14,-1],[12,3],[9,6],[4,8],[-1,9],[-5,8],[-10,9],[-14,6],[-16,2]];
 const yAt=(x:number,z:number,offset=.16)=>Math.sqrt(Math.max(0,radius*radius-x*x-z*z))+offset;
 const landVertices=[0,yAt(0,0,.2),0];for(const [x,z] of landOutline)landVertices.push(x,yAt(x,z,.2),z);
 const landIndices:number[]=[];for(let i=0;i<landOutline.length;i++)landIndices.push(0,i+1,(i+1)%landOutline.length+1);
 const landGeometry=geometry(new THREE.BufferGeometry());landGeometry.setAttribute('position',new THREE.Float32BufferAttribute(landVertices,3));landGeometry.setIndex(landIndices);landGeometry.computeVertexNormals();
 const land=new THREE.Mesh(landGeometry,remember(new THREE.MeshStandardMaterial({color:'#679a67',roughness:.86,flatShading:true})));land.castShadow=true;land.receiveShadow=true;root.add(land);
 const coastPoints=landOutline.map(([x,z])=>new THREE.Vector3(x,yAt(x,z,.3),z));coastPoints.push(coastPoints[0]);const coast=new THREE.Line(geometry(new THREE.BufferGeometry().setFromPoints(coastPoints)),remember(new THREE.LineBasicMaterial({color:'#d8e5bd',transparent:true,opacity:.88})));root.add(coast);
 const mountainMaterial=remember(new THREE.MeshStandardMaterial({color:'#3f765b',roughness:1,flatShading:true}));for(const [x,z,s] of [[11,-5,2.6],[8,-6.5,1.7],[12,-1.8,1.35],[6,-7.2,1.2]] as [number,number,number][]){const cone=new THREE.Mesh(geometry(new THREE.ConeGeometry(s,s*2.2,7)),mountainMaterial);cone.position.set(x,yAt(x,z)+s,z);cone.castShadow=true;root.add(cone)}
 const cityMaterial=remember(new THREE.MeshStandardMaterial({color:'#b6cec4',roughness:.45,metalness:.16}));for(const [x,z,h] of [[-2,1,2.7],[.2,.2,4.7],[3,2,3.3],[-5,-1,2.2],[-7,3,1.8],[5,-1,2.4]] as [number,number,number][]){const b=new THREE.Mesh(geometry(new THREE.BoxGeometry(.75,h,.75)),cityMaterial);b.position.set(x,yAt(x,z)+h/2,z);b.castShadow=true;root.add(b)}
 const starPositions=new Float32Array(330*3);let seed=84;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};for(let i=0;i<330;i++){const r=75+random()*75,a=random()*Math.PI*2,b=Math.acos(2*random()-1);starPositions[i*3]=r*Math.sin(b)*Math.cos(a);starPositions[i*3+1]=r*Math.cos(b);starPositions[i*3+2]=r*Math.sin(b)*Math.sin(a)}const starGeometry=geometry(new THREE.BufferGeometry());starGeometry.setAttribute('position',new THREE.BufferAttribute(starPositions,3));const stars=new THREE.Points(starGeometry,remember(new THREE.PointsMaterial({color:'#d9f3f0',size:.22,transparent:true,opacity:.65,depthWrite:false})));scene.add(stars);
 function labelTexture(location:MemoryLocation){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle=location.status==='ready'?'#f5ead3f2':'#0f3441dc';ctx.beginPath();ctx.roundRect(4,4,504,120,60);ctx.fill();ctx.strokeStyle=location.status==='ready'?'#ffcf79':'#79abb488';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=location.status==='ready'?'#163f47':'#d3e4e2';ctx.font='600 34px Arial, Microsoft YaHei';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(`${location.chapter}  ${location.shortName}`,256,65);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;textures.push(t);return t}
 const clickable:THREE.Object3D[]=[],labels:THREE.Sprite[]=[],beacons:THREE.Mesh[]=[];
 MEMORY_LOCATIONS.forEach(location=>{const {x,z}=location.planet,y=yAt(x,z,.5);const group=new THREE.Group();group.position.set(x,y,z);group.userData.location=location;root.add(group);const ready=location.status==='ready';const beaconMaterial=remember(new THREE.MeshStandardMaterial({color:ready?'#ffd07c':'#71abb0',emissive:ready?'#ff9e42':'#39747a',emissiveIntensity:ready?2:.45,roughness:.35}));const beacon=new THREE.Mesh(geometry(new THREE.OctahedronGeometry(ready?.55:.34)),beaconMaterial);beacon.userData.location=location;group.add(beacon);clickable.push(beacon);beacons.push(beacon);const ring=new THREE.Mesh(geometry(new THREE.RingGeometry(ready?.72:.5,ready?.88:.62,40)),remember(new THREE.MeshBasicMaterial({color:ready?'#ffd78f':'#76a9ae',transparent:true,opacity:ready?.85:.34,side:THREE.DoubleSide,depthWrite:false})));ring.rotation.x=-Math.PI/2;ring.position.y=-.42;ring.userData.location=location;group.add(ring);clickable.push(ring);const sprite=new THREE.Sprite(remember(new THREE.SpriteMaterial({map:labelTexture(location),transparent:true,depthTest:false,depthWrite:false})));sprite.position.y=ready?2.25:1.5;sprite.scale.set(ready?7.7:5.9,ready?1.9:1.48,1);sprite.renderOrder=8;sprite.userData.location=location;group.add(sprite);labels.push(sprite);clickable.push(sprite)});
 const pointer=new THREE.Vector2(),raycaster=new THREE.Raycaster();let downX=0,downY=0,dead=false,frame=0,last=performance.now(),elapsed=0,entering:MemoryLocation|null=null,enterProgress=0;const enterFrom=new THREE.Vector3(),enterTarget=new THREE.Vector3();
 function enterLocation(location:MemoryLocation){onSelect(location);if(location.status!=='ready'||entering)return;entering=location;enterProgress=0;enterFrom.copy(camera.position);const p=new THREE.Vector3(location.planet.x,yAt(location.planet.x,location.planet.z,.5),location.planet.z);root.localToWorld(p);enterTarget.copy(p.clone().normalize().multiplyScalar(radius+8));controls.enabled=false}
 const pointerDown=(e:PointerEvent)=>{downX=e.clientX;downY=e.clientY};const pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-downX,e.clientY-downY)>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(clickable,false)[0];if(hit)enterLocation(hit.object.userData.location)};const pointerMove=(e:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);renderer.domElement.style.cursor=raycaster.intersectObjects(clickable,false).length?'pointer':'grab'};renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pointerUp);renderer.domElement.addEventListener('pointermove',pointerMove);
 const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};const observer=new ResizeObserver(resize);observer.observe(host);
 function animate(now:number){if(dead)return;frame=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;elapsed+=dt;stars.rotation.y=elapsed*.006;beacons.forEach((b,i)=>{b.rotation.y=elapsed*(.55+i*.018);b.position.y=.1+Math.sin(elapsed*1.8+i)*.08});labels.forEach(s=>s.material.opacity=.86+.14*Math.sin(elapsed*1.2));if(entering){enterProgress=Math.min(1,enterProgress+dt/1.05);const t=1-Math.pow(1-enterProgress,3);camera.position.lerpVectors(enterFrom,enterTarget,t);camera.lookAt(new THREE.Vector3(entering.planet.x,yAt(entering.planet.x,entering.planet.z),entering.planet.z));if(enterProgress>=1){const target=entering;entering=null;onEnter(target)}}else controls.update();renderer.render(scene,camera)}frame=requestAnimationFrame(animate);
 return {enterLocation,zoom:(factor:number)=>{if(entering)return;const v=camera.position.clone().sub(controls.target).multiplyScalar(factor).clampLength(controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).add(v)},reset:()=>{if(entering)return;camera.position.set(43,35,48);controls.target.set(0,3,0);controls.update()},dispose:()=>{dead=true;cancelAnimationFrame(frame);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointerup',pointerUp);renderer.domElement.removeEventListener('pointermove',pointerMove);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();renderer.domElement.remove()}};
}
